# Generated by Django 5.2.13 on 2026-04-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_editora_cidade_editora_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
